from __future__ import annotations

import asyncio
import os
import sys
from typing import Any, Optional

import runpod

# RunPod's autogenerated Dockerfile `ADD . /` does not install the package,
# so we add `/src` to `sys.path` to import `hy_mt_mlx_server.*`.
sys.path.insert(0, "/src")

from hy_mt_mlx_server.imme import translate_imme, translate_text  # noqa: E402
from hy_mt_mlx_server.lang import detect_language_code, normalize_lang  # noqa: E402
from hy_mt_mlx_server.model import GenerationParams, HyMtTransformersModel  # noqa: E402


def _int_env(name: str, default: int) -> int:
    try:
        return int(os.environ.get(name, str(default)))
    except Exception:
        return default


def _float_env(name: str, default: float) -> float:
    try:
        return float(os.environ.get(name, str(default)))
    except Exception:
        return default


def _imme_batch(v: str) -> str:
    s = (v or "").strip().lower()
    if s in {"0", "false", "no", "off"}:
        return "off"
    if s in {"1", "true", "yes", "on"}:
        return "on"
    return "auto"


def _build_params() -> GenerationParams:
    return GenerationParams(
        max_new_tokens=_int_env("MAX_NEW_TOKENS", 1024),
        temperature=_float_env("TEMPERATURE", 0.0),
        top_p=_float_env("TOP_P", 0.6),
        top_k=_int_env("TOP_K", 20),
        repetition_penalty=_float_env("REPETITION_PENALTY", 1.05),
    )


def _default_max_input_chars() -> int:
    # Rough heuristic: keep chunks small enough that outputs don't get truncated by max_new_tokens.
    return min(2000, _int_env("MAX_NEW_TOKENS", 1024))


_MODEL_ID = os.environ.get("MODEL_ID", "tencent/HY-MT1.5-1.8B")
_DEVICE = os.environ.get("DEVICE", "cuda")
_DTYPE = os.environ.get("DTYPE", "float16")
_MAX_CONCURRENCY = _int_env("MODEL_MAX_CONCURRENCY", 1)

_MODEL = HyMtTransformersModel(_MODEL_ID, device=_DEVICE, dtype=_DTYPE, max_concurrency=_MAX_CONCURRENCY)


async def _handle(payload: dict[str, Any]) -> dict[str, Any]:
    action = payload.get("action") or payload.get("path") or payload.get("endpoint")
    if isinstance(action, str):
        a = action.strip().lstrip("/").lower()
    else:
        a = ""

    params = _build_params()
    max_input_chars = _int_env("MAX_INPUT_CHARS", _default_max_input_chars())
    imme_batch = _imme_batch(os.environ.get("IMME_BATCH", "auto"))
    imme_batch_size = _int_env("IMME_BATCH_SIZE", 32)
    imme_max_texts = _int_env("IMME_MAX_TEXTS", 1024)

    # Infer action by schema if not explicitly provided.
    if not a:
        if "text_list" in payload and "target_lang" in payload:
            a = "imme"
        elif "text" in payload and ("to" in payload or "target_lang" in payload):
            a = "translate"
        elif "text" in payload:
            a = "detect"

    if a == "detect":
        text = str(payload.get("text", ""))
        return {"language": detect_language_code(text)}

    if a in {"translate", "kiss"}:
        text = str(payload.get("text", ""))
        to_lang = normalize_lang(payload.get("to", payload.get("target_lang"))) or "en"
        from_lang_raw = payload.get("from", payload.get("from_lang", payload.get("source_lang")))
        from_lang = normalize_lang(from_lang_raw)
        detected = detect_language_code(text) if from_lang is None else from_lang
        out = await translate_text(_MODEL, text=text, to_lang=to_lang, params=params, max_input_chars=max_input_chars)
        return {"text": out, "from": detected, "to": to_lang}

    if a == "imme":
        text_list = payload.get("text_list", [])
        if not isinstance(text_list, list):
            raise ValueError("text_list must be a list")
        if not text_list:
            return {"translations": []}
        if imme_max_texts > 0 and len(text_list) > imme_max_texts:
            raise ValueError(f"text_list too large ({len(text_list)}); limit is IMME_MAX_TEXTS={imme_max_texts}")

        source_lang = normalize_lang(payload.get("source_lang"))
        target_lang = normalize_lang(payload.get("target_lang")) or "en"
        translations = await translate_imme(
            _MODEL,
            text_list=[str(t) for t in text_list],
            target_lang=target_lang,
            source_lang=source_lang,
            params=params,
            max_input_chars=max_input_chars,
            batch_mode=imme_batch,
            batch_size=imme_batch_size,
        )
        return {"translations": translations}

    raise ValueError("unrecognized input schema; provide action/path or fields like {text,to} / {target_lang,text_list}")


def handler(job: dict[str, Any]) -> dict[str, Any]:
    payload = job.get("input")
    if payload is None:
        payload = {}
    if not isinstance(payload, dict):
        raise ValueError("job.input must be an object")
    return asyncio.run(_handle(payload))


runpod.serverless.start({"handler": handler})

